### PR TITLE
Update to RespokeSDK cocoapod to version 1.1.0

### PR DESCRIPTION
**Pull request by robertcrabtree**
Changes include:
- sendMessage push flag
- onMessage didSend flag

### CODE REVIEW

**Comment by ruffrey** [comment]
:+1:

**Comment by chadxz** [comment]
:shipit:

**Comment by jznadams** [comment]
:+1:

**Comment by sudhaRani1** [comment]
My app is crashing in Production mode. I have used this code :
   if (!sharedRespokeClient)
                                                  {
                                                      // Create a Respoke client instance to be used for the duration of the application
                                                      sharedRespokeClient = [[Respoke sharedInstance] createClient];
                                                  }
                                                  sharedRespokeClient.delegate = self;

```
                                              [sharedRespokeClient connectWithTokenID:[PlacesDetails sharedInstance].tokenAccess initialPresence:nil errorHandler:^(NSString *errorMessage)
                                               {
                                                   NSLog(@"errorMessage..%@",errorMessage);
                                                   [self showError:errorMessage];
                                               }];
```

#pragma mark - RespokeClientDelegate
- (void)onConnect:(RespokeClient*)sender
  {
  
  NSString *groupName = @"121Date";
  
  sharedContactManager.username = [sender getEndpointID];
  
  [sharedContactManager joinGroups:@[groupName] successHandler:^(){
      NSLog(@"sucess");
  
  }
  errorHandler:^(NSString *errorMessage)
   {
            [self showError:errorMessage];
  }];
  }

**Pull request merged**
